name = "axiselect-web"
compatibility_date = "2024-12-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "axiselect-web"
compatibility_flags = ["nodejs_compat"]

